IF
  Global("NomoranSpawn","GLOBAL",0)
  Global("ZElminsterTalk","GLOBAL",0)
  GGT("CHAPTER","GLOBAL",19)
  !Global("NomoranPart1","GLOBAL",1)
THEN
  RESPONSE #100
    CreateCreature("z_nomora",[2139.1356],12)
    SetGlobal("NomoranSpawn","GLOBAL",1)
	SetGlobal("ZStartAddAct","GLOBAL",1) 
END

IF
  Global("ZElminsterTalk","GLOBAL",2)
THEN
  RESPONSE #100
    SetGlobal("ZElminsterTalk","GLOBAL",3)
    CreateCreature("z_elmi",[2139.1356],12)
    CreateCreature("z_zah",[2081.1336],12)
END